### PR TITLE
Title selection functionality

### PR DESCRIPTION
**Pull request by coding-in-public**

### CODE REVIEW

**Comment by coding-in-public** [comment]
Just update the data.ts file with your swifie moods and lyrics and it should work!

**Comment by christina-de-martinez** [comment]
Do the moods all need to have the same number of lyrics? Some of my categories are bigger than others right now.

**Comment by cpenned** [comment]
> Do the moods all need to have the same number of lyrics? Some of my categories are bigger than others right now.

No, the randomizing function takes the mood selected into consideration (at least it should :)

**Comment by coding-in-public** [comment]
No, the randomizing function takes the mood selected into consideration (at least it should :)

**Pull request merged**
